version: '3.7'
services:
  pgsql:
    image: postgres:12.1
    container_name: pgsql
    volumes:
      - ./data-postgresql:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      #the PostgreSQL image sets up trust authentication locally so
      #you may notice a password is not required when connecting from
      #localhost (inside the same container).
      #However, a password will be required if connecting from a different host/container.
      POSTGRES_IMG_VERSION : ${POSTGRES_IMG_VERSION}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}     
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_DB: ${POSTGRESQL_DEFAULT_DB}
      PGDATA: ${PGDATA}
      
  jdk8:
    build: container-jdk8

  karaf:
    build: container_karaf
    container_name: karaf
    volumes:
            - ./container_karaf/container_config_folder:/container_config_folder
            - ./container_karaf/deploy:/opt/karaf/deploy
            # - ./container_karaf/container_config_folder/etc:/opt/karaf/etc      
           
        #  - ./container_karaf/data:/opt/karaf/data  
    ports:
            - "1099:1099"
            - "4444:4444"
            - "8101:8101"
            - "8181:8181"
    depends_on:
      - jdk8

  



